/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package User.Validator.JUnit.Test;

import org.junit.Test;
import static org.junit.Assert.*;

import org.junit.Assert;

public class UserRegistrationJUnitTest {
	@Test
	public void TestValidateFirstName() {
		UserRegistrationJUnit firstNameValidator = new UserRegistrationJUnit();
		boolean found = firstNameValidator.FirstNameValidation("Soumik");
		Assert.assertTrue(found);
	}
}
