/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package User.Validator.JUnit.Test;

import org.junit.Test;
import static org.junit.Assert.*;

import org.junit.Assert;

public class UserRegistrationJUnitTest {
	
}
